In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_excel(r"C:\Users\Rahul\Desktop\data anylist\excel\Projects\pharmacutical project\Pharmaceutical_sales_ data.xlsx",sheet_name="Data")

In [6]:
df.shape

(254082, 18)

In [7]:
cols = df.columns

cols

Index(['Distributor', 'Customer Name', 'City', 'Country', 'Latitude',
       'Longitude', 'Channel', 'Sub-channel', 'Product Name', 'Product Class',
       'Quantity', 'Price', 'Sales', 'Month', 'Year', 'Name of Sales Rep',
       'Manager', 'Sales Team'],
      dtype='object')

In [8]:
df.head(10)

,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,Product Name,Product Class,Quantity,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team
0,Gottlieb-Cruickshank,"Zieme, Doyle and Kunze",Lublin,Poland,51.2333,22.5667,Hospital,Private,Topipizole,Mood Stabilizers,4.0,368,1472.0,January,2018,Mary Gerrard,Britanny Bold,Delta
1,Gottlieb-Cruickshank,Feest PLC,Świecie,Poland,53.4167,18.4333,Pharmacy,Retail,Choriotrisin,Antibiotics,7.0,591,4137.0,January,2018,Jessica Smith,Britanny Bold,Delta
2,Gottlieb-Cruickshank,Medhurst-Beer Pharmaceutical Limited,Rybnik,Poland,50.0833,18.5000,Pharmacy,Institution,Acantaine,Antibiotics,30.0,66,1980.0,January,2018,Steve Pepple,Tracy Banks,Bravo
3,Gottlieb-Cruickshank,Barton Ltd Pharma Plc,Czeladź,Poland,50.3333,19.0833,Hospital,Private,Lioletine Refliruvax,Analgesics,6.0,435,2610.0,January,2018,Mary Gerrard,Britanny Bold,Delta
4,Gottlieb-Cruickshank,Keeling LLC Pharmacy,Olsztyn,Poland,53.7800,20.4942,Pharmacy,Retail,Oxymotroban Fexoformin,Analgesics,20.0,458,9160.0,January,2018,Anne Wu,Britanny Bold,Delta
5,Gottlieb-Cruickshank,Runte-Marquardt Pharmaceutical Ltd,Olecko,Poland,54.0333,22.5000,Hospital,Private,Pazofenac,Mood Stabilizers,5.0,123,615.0,January,2018,Thompson Crawford,James Goodwill,Alfa
6,Gottlieb-Cruickshank,"Blick, Pacocha and Schowalter",Inowrocław,Poland,52.7958,18.2611,Pharmacy,Retail,Symbitrim,Analgesics,20.0,536,10720.0,January,2018,Sheila Stones,Britanny Bold,Delta
7,Gottlieb-Cruickshank,Leuschke PLC Pharmacy,Ciechanów,Poland,52.8817,20.6106,Pharmacy,Retail,Morphizolid Tianalin,Mood Stabilizers,5.0,742,3710.0,January,2018,Mary Gerrard,Britanny Bold,Delta
8,Gottlieb-Cruickshank,Miller-Satterfield Pharma Plc,Nidzica,Poland,53.3583,20.4250,Hospital,Private,Lovapur,Mood Stabilizers,4.0,551,2204.0,January,2018,Stella Given,Alisha Cordwell,Charlie
9,Gottlieb-Cruickshank,Bashirian-Kassulke Pharma Plc,Kraków,Poland,50.0614,19.9372,Hospital,Private,Ampysin,Analgesics,10.0,243,2430.0,January,2018,Morris Garcia,Tracy Banks,Bravo

In [9]:
df.sample(n=10)

,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,Product Name,Product Class,Quantity,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team
67043,Welch-Langworth,Doyle-Tillman Pharmaceutical Limited,Zirndorf,Germany,49.4500,10.9500,Pharmacy,Institution,Megenorphine,Antimalarial,7.0,402,2814.0,June,2017,Steve Pepple,Tracy Banks,Bravo
77503,Gerlach LLC,Kreiger Inc,Burgdorf,Germany,52.4500,10.0083,Pharmacy,Retail,Victomax,Analgesics,5.0,623,3115.0,August,2017,Jimmy Grey,Alisha Cordwell,Charlie
153598,Gerlach LLC,"Sanford, Franecki and Greenholt Pharma Plc",Waltrop,Germany,51.6167,7.3833,Hospital,Government,Pentastrin,Antibiotics,5.0,497,2485.0,January,2019,Daniel Gates,Alisha Cordwell,Charlie
217338,Gerlach LLC,Gulgowski-Vandervort Pharm,Rathenow,Germany,52.6000,12.3333,Hospital,Private,Robapril,Antipiretics,1.0,453,453.0,April,2020,Jessica Smith,Britanny Bold,Delta
103641,Gerlach LLC,"Johns, Mueller and Nitzsche",Magdeburg,Germany,52.1278,11.6292,Hospital,Government,Epzipitant,Analgesics,5.0,778,3890.0,February,2018,Abigail Thompson,Tracy Banks,Bravo
122218,Gerlach LLC,Wolff Group,Pfungstadt,Germany,49.8056,8.6044,Pharmacy,Retail,Quiniprosyn,Antiseptics,70.0,445,31150.0,June,2018,Stella Given,Alisha Cordwell,Charlie
134108,Gerlach LLC,Mills Inc Pharmaceutical Ltd,Emsdetten,Germany,52.1728,7.5344,Hospital,Private,Dasagestin,Analgesics,10.0,386,3860.0,September,2018,Steve Pepple,Tracy Banks,Bravo
48309,Erdman,Stanton-Cole Pharmacy,Düren,Germany,50.8000,6.4833,Pharmacy,Institution,Lansostral Acgestin,Antiseptics,50.0,627,31350.0,February,2017,Mary Gerrard,Britanny Bold,Delta
77711,Koss,"Johns, Mueller and Nitzsche Pharma Plc",Hemer,Germany,51.3833,7.7667,Pharmacy,Institution,Thalilamide,Antibiotics,10.0,615,6150.0,August,2017,Daniel Gates,Alisha Cordwell,Charlie
145564,Gerlach LLC,Abernathy and Sons,Freiburg im Breisgau,Germany,47.9947,7.8497,Pharmacy,Retail,Halciramine,Antimalarial,20.0,409,8180.0,November,2018,Jessica Smith,Britanny Bold,Delta

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254082 entries, 0 to 254081
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Distributor        254082 non-null  object
 1   Customer Name      254082 non-null  object
 2   City               254082 non-null  object
 3   Country            254082 non-null  object
 4   Latitude           254082 non-null  float64
 5   Longitude          254082 non-null  float64
 6   Channel            254082 non-null  object
 7   Sub-channel        254082 non-null  object
 8   Product Name       254082 non-null  object
 9   Product Class      254082 non-null  object
 10  Quantity           254082 non-null  float64
 11  Price              254082 non-null  int64
 12  Sales              254082 non-null  float64
 13  Month              254082 non-null  object
 14  Year               254082 non-null  int64
 15  Name of Sales Rep  254082 non-null  object
 16  Manager            254082 non-null  object
 17  Sales Team         254082 non-null  object
dtypes: float64(4), int64(2), object(12)
memory usage: 34.9+ MB

In [11]:
df.describe()

,Latitude,Longitude,Quantity,Price,Sales,Year
count,254082.000000,254082.000000,254082.000000,254082.000000,2.540820e+05,254082.000000
mean,50.962222,10.803212,112.872139,412.207720,4.643772e+04,2018.385187
std,1.625526,4.143311,744.310385,224.963687,3.491918e+05,1.041352
min,47.514200,6.083800,-7200.000000,22.000000,-4.161600e+06,2017.000000
25%,49.805600,7.891100,5.000000,195.000000,1.704000e+03,2018.000000
50%,51.133300,9.397800,20.000000,430.000000,5.850000e+03,2018.000000
75%,52.083300,12.133300,50.000000,605.000000,2.156525e+04,2019.000000
max,54.781900,23.566700,117600.000000,794.000000,7.420560e+07,2020.000000

In [12]:
df['Year'].astype(int)

0         2018
1         2018
2         2018
3         2018
4         2018
          ...
254077    2020
254078    2020
254079    2020
254080    2020
254081    2020
Name: Year, Length: 254082, dtype: int32

In [13]:
df['Quantity'].astype(int)

0            4
1            7
2           30
3            6
4           20
          ...
254077     919
254078     432
254079     320
254080     565
254081    1080
Name: Quantity, Length: 254082, dtype: int32

In [14]:
df.isnull().sum()

Distributor          0
Customer Name        0
City                 0
Country              0
Latitude             0
Longitude            0
Channel              0
Sub-channel          0
Product Name         0
Product Class        0
Quantity             0
Price                0
Sales                0
Month                0
Year                 0
Name of Sales Rep    0
Manager              0
Sales Team           0
dtype: int64

In [15]:
df.nunique()

Distributor             29
Customer Name          751
City                   749
Country                  2
Latitude               655
Longitude              709
Channel                  2
Sub-channel              4
Product Name           240
Product Class            6
Quantity              1735
Price                  210
Sales                20546
Month                   12
Year                     4
Name of Sales Rep       13
Manager                  4
Sales Team               4
dtype: int64

In [16]:
df[(df['Quantity']<0)].sort_values(by = 'Quantity')

,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,Product Name,Product Class,Quantity,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team
146874,Erdman,Gottlieb-Koss Pharm,Hattingen,Germany,51.3992,7.1858,Pharmacy,Institution,Penitrana,Analgesics,-7200.0,179,-1288800.0,November,2018,Jessica Smith,Britanny Bold,Delta
186202,Koss,Welch-Orn Pharm,Emden,Germany,53.3669,7.2061,Hospital,Private,Dantolac Pazocor,Analgesics,-7200.0,578,-4161600.0,August,2019,Sheila Stones,Britanny Bold,Delta
147048,Koss,"Armstrong, Medhurst and Bogisich Pharmacy",Lehrte,Germany,52.3725,9.9769,Hospital,Government,Exexone,Mood Stabilizers,-5407.0,239,-1292273.0,November,2018,Jessica Smith,Britanny Bold,Delta
221786,Koss,Dach PLC,Deggendorf,Germany,48.8353,12.9644,Hospital,Private,Ketamara Evogel,Antipiretics,-4500.0,704,-3168000.0,May,2020,Daniel Gates,Alisha Cordwell,Charlie
246505,Kozey-Emmerich,"Torphy, Pfeffer and Jakubowski Pharmaceutical Ltd",Leipzig,Germany,51.3500,12.3833,Pharmacy,Retail,Dexacilin Triline,Analgesics,-3500.0,129,-451500.0,November,2020,Anne Wu,Britanny Bold,Delta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54195,Gerlach LLC,"Kuphal, D'Amore and Bode Pharm",Cologne,Germany,50.9422,6.9578,Hospital,Government,Quixitriptan Alanesin,Antiseptics,-1.0,79,-79.0,April,2017,Alan Ray,James Goodwill,Alfa
88021,Koss,Raynor-Graham Pharma Plc,Saarbrücken,Germany,49.2333,7.0000,Pharmacy,Institution,Lovepion,Antiseptics,-1.0,544,-544.0,November,2017,Erica Jones,James Goodwill,Alfa
88020,Koss,Purdy Ltd,Erkelenz,Germany,51.0800,6.3156,Pharmacy,Retail,Veratorol Ciclovatol,Mood Stabilizers,-1.0,154,-154.0,November,2017,Anne Wu,Britanny Bold,Delta
245512,Gerlach LLC,Reinger Group Pharma Plc,Weil am Rhein,Germany,47.5947,7.6108,Pharmacy,Institution,Ceretosine,Antiseptics,-1.0,343,-343.0,November,2020,Morris Garcia,Tracy Banks,Bravo
234743,Koss,"Daniel, Baumbach and Nitzsche",Steinheim am Main,Germany,50.1257,8.8300,Hospital,Private,Pulmofine,Antibiotics,-1.0,688,-688.0,August,2020,Anne Wu,Britanny Bold,Delta

In [17]:
df['Quantity'] = df['Quantity'].abs()

In [18]:
df

,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,Product Name,Product Class,Quantity,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team
0,Gottlieb-Cruickshank,"Zieme, Doyle and Kunze",Lublin,Poland,51.2333,22.5667,Hospital,Private,Topipizole,Mood Stabilizers,4.0,368,1472.0,January,2018,Mary Gerrard,Britanny Bold,Delta
1,Gottlieb-Cruickshank,Feest PLC,Świecie,Poland,53.4167,18.4333,Pharmacy,Retail,Choriotrisin,Antibiotics,7.0,591,4137.0,January,2018,Jessica Smith,Britanny Bold,Delta
2,Gottlieb-Cruickshank,Medhurst-Beer Pharmaceutical Limited,Rybnik,Poland,50.0833,18.5000,Pharmacy,Institution,Acantaine,Antibiotics,30.0,66,1980.0,January,2018,Steve Pepple,Tracy Banks,Bravo
3,Gottlieb-Cruickshank,Barton Ltd Pharma Plc,Czeladź,Poland,50.3333,19.0833,Hospital,Private,Lioletine Refliruvax,Analgesics,6.0,435,2610.0,January,2018,Mary Gerrard,Britanny Bold,Delta
4,Gottlieb-Cruickshank,Keeling LLC Pharmacy,Olsztyn,Poland,53.7800,20.4942,Pharmacy,Retail,Oxymotroban Fexoformin,Analgesics,20.0,458,9160.0,January,2018,Anne Wu,Britanny Bold,Delta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254077,Bashirian-Kassulke,"Koch, Borer and Hagenes Pharmaceutical Ltd",Lauf,Germany,49.5103,11.2772,Hospital,Private,Pentastrin,Antibiotics,919.0,497,456743.0,December,2020,Thompson Crawford,James Goodwill,Alfa
254078,Bashirian-Kassulke,Hane Ltd Pharmaceutical Ltd,Aichach,Germany,48.4500,11.1333,Hospital,Private,Abranatal Lysoprosate,Antiseptics,432.0,681,294192.0,December,2020,Anne Wu,Britanny Bold,Delta
254079,Bashirian-Kassulke,Harris-Conroy Pharmacy,Wilhelmshaven,Germany,53.5167,8.1333,Pharmacy,Retail,Adideine,Mood Stabilizers,320.0,678,216960.0,December,2020,Abigail Thompson,Tracy Banks,Bravo
254080,Bashirian-Kassulke,Balistreri Group Pharm,Böblingen,Germany,48.6833,9.0000,Hospital,Government,Feruprazole,Mood Stabilizers,565.0,115,64975.0,December,2020,Stella Given,Alisha Cordwell,Charlie
254081,Bashirian-Kassulke,"Heathcote, Kovacek and Parker",Hof,Germany,50.3167,11.9167,Pharmacy,Retail,Feruprazole,Mood Stabilizers,1080.0,115,124200.0,December,2020,Alan Ray,James Goodwill,Alfa

In [19]:
df[(df['Quantity']<0)].sort_values(by = 'Quantity')

Empty DataFrame
Columns: [Distributor, Customer Name, City, Country, Latitude, Longitude, Channel, Sub-channel, Product Name, Product Class, Quantity, Price, Sales, Month, Year, Name of Sales Rep, Manager, Sales Team]
Index: []

In [20]:
df[df['Sales']<0].head()

,Distributor,Customer Name,City,Country,Latitude,Longitude,Channel,Sub-channel,Product Name,Product Class,Quantity,Price,Sales,Month,Year,Name of Sales Rep,Manager,Sales Team
3761,Rohan,"Zieme, Doyle and Kunze",Lublin,Poland,51.2333,22.5667,Hospital,Private,Exotropin Empizine,Mood Stabilizers,19.0,785,-14915.0,February,2018,Anne Wu,Britanny Bold,Delta
3762,Rohan,Nader-Gaylord Pharmaceutical Limited,Sobótka,Poland,50.8986,16.7444,Hospital,Private,Epzipitant,Analgesics,12.0,778,-9336.0,February,2018,Thompson Crawford,James Goodwill,Alfa
18526,Rohan,"Buckridge, Dach and Carroll Pharmaceutical Lim...",Luboń,Poland,52.3333,16.8833,Hospital,Private,Belavarix Benzabicin,Antibiotics,1.0,131,-131.0,November,2018,Morris Garcia,Tracy Banks,Bravo
22613,Prohaska-Kuhic,"Wiegand, Jast and Yost Pharma Plc",Płock,Poland,52.5500,19.7000,Hospital,Private,Afinitasol,Antipiretics,5.0,286,-1430.0,February,2018,Jessica Smith,Britanny Bold,Delta
22751,Prohaska-Kuhic,Pfeffer-Hodkiewicz Pharmaceutical Ltd,Szczytno,Poland,53.5628,20.9853,Hospital,Government,Sucprine Specbalamin,Antiseptics,50.0,182,-9100.0,March,2018,Jimmy Grey,Alisha Cordwell,Charlie

In [21]:
df['Sales'] = df['Sales'].abs()

In [22]:
df[df['Sales']<0]

Empty DataFrame
Columns: [Distributor, Customer Name, City, Country, Latitude, Longitude, Channel, Sub-channel, Product Name, Product Class, Quantity, Price, Sales, Month, Year, Name of Sales Rep, Manager, Sales Team]
Index: []

In [23]:
df['Cumilative Sales'] = df['Sales'].cumsum()

In [24]:
Yearwise_Sales =  pd.DataFrame(df.groupby('Year')['Sales'].sum())

Yearwise_Sales

             Sales
Year
2017  2.734379e+09
2018  3.584303e+09
2019  2.995829e+09
2020  2.777436e+09

In [25]:
Yearwise_Sales['YoY Diffrence'] = Yearwise_Sales['Sales'].iloc[0:].diff()

Yearwise_Sales

             Sales  YoY Diffrence
Year
2017  2.734379e+09            NaN
2018  3.584303e+09   8.499236e+08
2019  2.995829e+09  -5.884732e+08
2020  2.777436e+09  -2.183936e+08

In [26]:
Yearwise_Sales['YoY Growth'] = (Yearwise_Sales['YoY Diffrence']/Yearwise_Sales['Sales'])*100
Yearwise_Sales['YoY Diffrence'] = Yearwise_Sales['YoY Diffrence'].fillna(0)
Yearwise_Sales['YoY Growth'] = Yearwise_Sales['YoY Growth'].fillna(0)

In [27]:
Yearwise_Sales

             Sales  YoY Diffrence  YoY Growth
Year
2017  2.734379e+09   0.000000e+00    0.000000
2018  3.584303e+09   8.499236e+08   23.712384
2019  2.995829e+09  -5.884732e+08  -19.643082
2020  2.777436e+09  -2.183936e+08   -7.863137

In [29]:
with pd.ExcelWriter('Proccessed data.xlsx') as writer:
    df.to_excel(writer, sheet_name='Data')
    Yearwise_Sales.to_excel(writer, sheet_name='Yearwise Sales')